// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIlpx_g4T6z3rHmnjWK0iH_zhfDfGcHwc',
    appId: '1:154149889779:android:a5d6d9eabc6e2f8f357986',
    messagingSenderId: '154149889779',
    projectId: 'flutter-test-assignment-cd6e0',
    storageBucket: 'flutter-test-assignment-cd6e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2XI18UVev2b2OGLwtxHHlhDoW_z_TA5o',
    appId: '1:154149889779:ios:1b2730c3ef3dfab9357986',
    messagingSenderId: '154149889779',
    projectId: 'flutter-test-assignment-cd6e0',
    storageBucket: 'flutter-test-assignment-cd6e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2XI18UVev2b2OGLwtxHHlhDoW_z_TA5o',
    appId: '1:154149889779:ios:1b2730c3ef3dfab9357986',
    messagingSenderId: '154149889779',
    projectId: 'flutter-test-assignment-cd6e0',
    storageBucket: 'flutter-test-assignment-cd6e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestAssignment',
  );
}
